name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Create an agent with...
        2. Run the command...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: If applicable, add logs or error output
      render: shell

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - "@cogitator-ai/core"
        - "@cogitator-ai/cli"
        - "@cogitator-ai/config"
        - "@cogitator-ai/deploy"
        - "@cogitator-ai/types"
        - "@cogitator-ai/memory"
        - "@cogitator-ai/swarms"
        - "@cogitator-ai/workflows"
        - "@cogitator-ai/a2a"
        - "@cogitator-ai/mcp"
        - "@cogitator-ai/express"
        - "@cogitator-ai/fastify"
        - "@cogitator-ai/hono"
        - "@cogitator-ai/koa"
        - "@cogitator-ai/next"
        - "@cogitator-ai/dashboard"
        - "@cogitator-ai/models"
        - "@cogitator-ai/sandbox"
        - "@cogitator-ai/ai-sdk"
        - "@cogitator-ai/neuro-symbolic"
        - "Other"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using? (check package.json or `npm ls`)
      placeholder: "0.17.0"

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - Node.js
        - Bun
        - Deno
        - Other

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
