name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered

  - type: dropdown
    id: package
    attributes:
      label: Related Package
      description: Which package would this feature affect?
      options:
        - "@cogitator-ai/core"
        - "@cogitator-ai/cli"
        - "@cogitator-ai/config"
        - "@cogitator-ai/deploy"
        - "@cogitator-ai/types"
        - "@cogitator-ai/memory"
        - "@cogitator-ai/swarms"
        - "@cogitator-ai/workflows"
        - "@cogitator-ai/a2a"
        - "@cogitator-ai/mcp"
        - "@cogitator-ai/express"
        - "@cogitator-ai/fastify"
        - "@cogitator-ai/hono"
        - "@cogitator-ai/koa"
        - "@cogitator-ai/next"
        - "@cogitator-ai/dashboard"
        - "@cogitator-ai/models"
        - "@cogitator-ai/sandbox"
        - "@cogitator-ai/ai-sdk"
        - "@cogitator-ai/neuro-symbolic"
        - "New package"
        - "Not sure"

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
