import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { ArtifactGenerator, ProjectAnalyzer } from '@cogitator-ai/deploy';
import { code } from '../code.js';
import { LOCKFILES, runScript } from '../package-manager.js';
import type { ProjectBuilder } from '../project.js';
import type { FeatureModule } from './types.js';

/** Deploy artifacts the project keeps at its root, from what @cogitator-ai/deploy generates. */
const ROOT_ARTIFACTS: Record<string, string> = {
  Dockerfile: 'Dockerfile',
  '.dockerignore': '.dockerignore',
  'fly.toml': 'fly.toml',
};

/**
 * Generates the Dockerfile, `.dockerignore` and `fly.toml` with
 * `@cogitator-ai/deploy` itself: the planned project is laid out in a temporary
 * directory, analyzed the way `cogitator deploy` analyzes it, and the artifacts
 * of its generator are kept. There is one Dockerfile template, the deployer's.
 * The lockfile the install writes is stood in for, since the image installs
 * from it.
 */
export function emitDeployArtifacts(project: ProjectBuilder): void {
  const { spec } = project;
  if (spec.deploy === 'none') return;

  const dir = mkdtempSync(join(tmpdir(), 'cogitator-deploy-plan-'));
  try {
    for (const file of project.files.values()) {
      const target = join(dir, file.path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, file.content);
    }
    writeFileSync(join(dir, LOCKFILES[spec.packageManager]), '');

    const analysis = new ProjectAnalyzer().analyze(dir, { target: spec.deploy }, { env: {} });
    const { files } = new ArtifactGenerator().generate(analysis.deployConfig, analysis);
    for (const artifact of files) {
      const path = ROOT_ARTIFACTS[artifact.path];
      if (path) project.file(path, artifact.content);
    }
    for (const warning of analysis.warnings) project.warn(`deploy: ${warning}`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** A production Dockerfile and the deploy settings for Docker or Fly.io. */
export const deployFeature: FeatureModule = {
  id: 'deploy',
  applies: (spec) => spec.deploy !== 'none',
  apply(project) {
    const { spec } = project;
    const pm = spec.packageManager;
    project
      .script('deploy', 'cogitator deploy')
      .script('deploy:plan', 'cogitator deploy --dry-run');
    project.readmeSection(
      'Deploy',
      code`
        \`Dockerfile\` is a multi-stage production image generated by \`@cogitator-ai/deploy\` from \`cogitator.yml\`: it installs from the lockfile, builds, and runs as an unprivileged user with only production dependencies.${spec.deploy === 'fly' ? ' `fly.toml` configures the Fly.io app.' : ''}

        \`\`\`bash
        ${runScript(pm, 'deploy:plan')}  # what would be deployed, with checks for secrets and services
        ${runScript(pm, 'deploy')}       # build and ${spec.deploy === 'fly' ? 'deploy to Fly.io' : 'run with Docker'}
        \`\`\`

        Secrets listed under \`deploy.secrets\` in \`cogitator.yml\` must be set in the environment you deploy from.
      `
    );
    project.section(
      'Deploy',
      code`
        \`cogitator.yml\` (\`deploy\`) says how the project ships: target ${spec.deploy}, the secrets a deployment needs, the health check. \`${runScript(pm, 'deploy:plan')}\` checks it without deploying, \`${runScript(pm, 'deploy')}\` deploys. \`Dockerfile\` and \`.dockerignore\` come from \`@cogitator-ai/deploy\`; change \`cogitator.yml\` rather than the Dockerfile, \`cogitator deploy\` generates its image from it.
      `
    );
  },
};
