export {
  SelfModifyingAgent,
  type SelfModifyingAgentOptions,
  type SelfModifyingAgentConfig,
  type SelfModifyingEventDataMap,
  type TypedSelfModifyingEvent,
  type RunContext,
} from './self-modifying-agent';

export {
  GapAnalyzer,
  ToolGenerator,
  ToolValidator,
  ToolSandbox,
  InMemoryGeneratedToolStore,
  DEFAULT_SANDBOX_CONFIG,
  TOOL_GENERATION_SYSTEM_PROMPT,
  buildGapAnalysisPrompt,
  buildToolGenerationPrompt,
  buildToolValidationPrompt,
  buildToolImprovementPrompt,
  parseGapAnalysisResponse,
  parseToolGenerationResponse,
  parseValidationResponse,
  type ToolReview,
  type GapAnalyzerOptions,
  type GapAnalysisContext,
  type ToolGeneratorOptions,
  type ToolValidatorOptions,
  type ValidationRule,
  type SandboxTestCase,
  type GenerateOptions,
  type GenerationResult,
  type ToolUsageRecord,
  type ToolMetrics,
} from './tool-generation';

export {
  MetaReasoner,
  ObservationCollector,
  StrategySelector,
  DEFAULT_META_REASONING_CONFIG,
  DEFAULT_MODE_PROFILES,
  buildMetaAssessmentPrompt,
  parseMetaAssessmentResponse,
  META_REASONING_SYSTEM_PROMPT,
  mergeModeProfiles,
  type MetaReasonerOptions,
  type MetaReasoningOverrides,
  type ModeProfileOverrides,
  type StrategySelectorOptions,
  type ActionRecord,
  type ObservationContext,
  type ModeScore,
} from './meta-reasoning';

export {
  CapabilityAnalyzer,
  EvolutionStrategy,
  ParameterOptimizer,
  ARCHITECTURE_ANALYSIS_SYSTEM_PROMPT,
  buildTaskProfilePrompt,
  buildCandidateGenerationPrompt,
  buildPerformanceAnalysisPrompt,
  parseTaskProfileResponse,
  parseCandidateGenerationResponse,
  parsePerformanceAnalysisResponse,
  sanitizeCandidateConfig,
  type CapabilityAnalyzerOptions,
  type EvolutionStrategyOptions,
  type ParameterOptimizerOptions,
  type SelectionResult,
  type OptimizationResult,
  type HistoricalRecord,
} from './architecture-evolution';

export {
  ModificationValidator,
  RollbackManager,
  InMemoryCheckpointStore,
  DEFAULT_SAFETY_CONSTRAINTS,
  DEFAULT_CAPABILITY_CONSTRAINTS,
  DEFAULT_RESOURCE_CONSTRAINTS,
  createDefaultConstraints,
  mergeConstraints,
  mergeSafetyConstraints,
  mergeCapabilityConstraints,
  mergeResourceConstraints,
  mergeCustomConstraints,
  type ModificationValidatorOptions,
  type RollbackManagerOptions,
  type CheckpointStore,
  type CheckpointDiff,
} from './constraints';

export { SelfModifyingEventEmitter, type SelfModifyingEventHandler } from './events';

export { llmChat, extractJson } from './utils';

export type {
  SelfModifyingConfig,
  ToolSelfGenerationConfig,
  MetaReasoningConfig,
  ArchitectureEvolutionConfig,
  ModificationConstraintsConfig,
  ToolGenerationRequest,
  GeneratedTool,
  ToolValidationResult,
  ToolSandboxConfig,
  ToolSandboxResult,
  GeneratedToolStore,
  CapabilityGap,
  GapAnalysisResult,
  ReasoningMode,
  ReasoningModeConfig,
  MetaObservation,
  MetaAssessment,
  MetaAdaptation,
  MetaTrigger,
  TaskProfile,
  ArchitectureConfig,
  EvolutionCandidate,
  EvolutionMetrics,
  EvolutionStrategy as IEvolutionStrategy,
  EvolvableParameter,
  ModificationRequest,
  ModificationConstraints,
  ModificationValidationResult,
  ModificationCheckpoint,
  AppliedModification,
  SafetyConstraint,
  CapabilityConstraint,
  ResourceConstraint,
  SelfModifyingEvent,
} from '@cogitator-ai/types';
