/**
 * ISO 3166-1 alpha-2 codes of the countries Tavily can boost results for, mapped to the names
 * its `country` parameter takes.
 */
export const TAVILY_COUNTRIES: Readonly<Record<string, string>> = {
  AD: 'andorra',
  AE: 'united arab emirates',
  AF: 'afghanistan',
  AL: 'albania',
  AM: 'armenia',
  AO: 'angola',
  AR: 'argentina',
  AT: 'austria',
  AU: 'australia',
  AZ: 'azerbaijan',
  BA: 'bosnia and herzegovina',
  BB: 'barbados',
  BD: 'bangladesh',
  BE: 'belgium',
  BF: 'burkina faso',
  BG: 'bulgaria',
  BH: 'bahrain',
  BI: 'burundi',
  BJ: 'benin',
  BN: 'brunei',
  BO: 'bolivia',
  BR: 'brazil',
  BS: 'bahamas',
  BT: 'bhutan',
  BW: 'botswana',
  BY: 'belarus',
  BZ: 'belize',
  CA: 'canada',
  CF: 'central african republic',
  CG: 'congo',
  CH: 'switzerland',
  CL: 'chile',
  CM: 'cameroon',
  CN: 'china',
  CO: 'colombia',
  CR: 'costa rica',
  CU: 'cuba',
  CV: 'cape verde',
  CY: 'cyprus',
  CZ: 'czech republic',
  DE: 'germany',
  DJ: 'djibouti',
  DK: 'denmark',
  DO: 'dominican republic',
  DZ: 'algeria',
  EC: 'ecuador',
  EE: 'estonia',
  EG: 'egypt',
  ER: 'eritrea',
  ES: 'spain',
  ET: 'ethiopia',
  FI: 'finland',
  FJ: 'fiji',
  FR: 'france',
  GA: 'gabon',
  GB: 'united kingdom',
  GE: 'georgia',
  GH: 'ghana',
  GM: 'gambia',
  GN: 'guinea',
  GQ: 'equatorial guinea',
  GR: 'greece',
  GT: 'guatemala',
  HN: 'honduras',
  HR: 'croatia',
  HT: 'haiti',
  HU: 'hungary',
  ID: 'indonesia',
  IE: 'ireland',
  IL: 'israel',
  IN: 'india',
  IQ: 'iraq',
  IR: 'iran',
  IS: 'iceland',
  IT: 'italy',
  JM: 'jamaica',
  JO: 'jordan',
  JP: 'japan',
  KE: 'kenya',
  KG: 'kyrgyzstan',
  KH: 'cambodia',
  KM: 'comoros',
  KP: 'north korea',
  KR: 'south korea',
  KW: 'kuwait',
  KZ: 'kazakhstan',
  LB: 'lebanon',
  LI: 'liechtenstein',
  LK: 'sri lanka',
  LR: 'liberia',
  LS: 'lesotho',
  LT: 'lithuania',
  LU: 'luxembourg',
  LV: 'latvia',
  LY: 'libya',
  MA: 'morocco',
  MC: 'monaco',
  MD: 'moldova',
  ME: 'montenegro',
  MG: 'madagascar',
  MK: 'north macedonia',
  ML: 'mali',
  MM: 'myanmar',
  MN: 'mongolia',
  MR: 'mauritania',
  MT: 'malta',
  MU: 'mauritius',
  MV: 'maldives',
  MW: 'malawi',
  MX: 'mexico',
  MY: 'malaysia',
  MZ: 'mozambique',
  NA: 'namibia',
  NE: 'niger',
  NG: 'nigeria',
  NI: 'nicaragua',
  NL: 'netherlands',
  NO: 'norway',
  NP: 'nepal',
  NZ: 'new zealand',
  OM: 'oman',
  PA: 'panama',
  PE: 'peru',
  PG: 'papua new guinea',
  PH: 'philippines',
  PK: 'pakistan',
  PL: 'poland',
  PT: 'portugal',
  PY: 'paraguay',
  QA: 'qatar',
  RO: 'romania',
  RS: 'serbia',
  RU: 'russia',
  RW: 'rwanda',
  SA: 'saudi arabia',
  SD: 'sudan',
  SE: 'sweden',
  SG: 'singapore',
  SI: 'slovenia',
  SK: 'slovakia',
  SN: 'senegal',
  SO: 'somalia',
  SS: 'south sudan',
  SV: 'el salvador',
  SY: 'syria',
  TD: 'chad',
  TG: 'togo',
  TH: 'thailand',
  TJ: 'tajikistan',
  TM: 'turkmenistan',
  TN: 'tunisia',
  TR: 'turkey',
  TT: 'trinidad and tobago',
  TW: 'taiwan',
  TZ: 'tanzania',
  UA: 'ukraine',
  UG: 'uganda',
  US: 'united states',
  UY: 'uruguay',
  UZ: 'uzbekistan',
  VE: 'venezuela',
  VN: 'vietnam',
  YE: 'yemen',
  ZA: 'south africa',
  ZM: 'zambia',
  ZW: 'zimbabwe',
};
