export { NeuroSymbolic, createNeuroSymbolic, type NeuroSymbolicOptions } from './orchestrator';

export {
  createNeuroSymbolicTools,
  createLogicTools,
  createConstraintTools,
  createPlanningTools,
  createGraphTools,
  type NeuroSymbolicTools,
  type NeuroSymbolicToolsOptions,
} from './tools';

export {
  MemoryGraphAdapter,
  createMemoryGraphAdapter,
  PostgresGraphAdapter,
  createPostgresGraphAdapter,
  Neo4jGraphAdapter,
  createNeo4jGraphAdapter,
  type PostgresGraphAdapterConfig,
  type Neo4jGraphAdapterConfig,
} from './knowledge-graph/adapters';

export {
  unify,
  applySubstitution,
  composeSubstitutions,
  getVariables,
  renameVariables,
  termsEqual,
  occursIn,
  termToString,
  substitutionToString,
  isAtom,
  isVariable,
  isNumber,
  isString,
  isCompound,
  isList,
  parseTerm,
  parseClause,
  parseProgram,
  parseQuery,
  termFromValue,
  termToValue,
  KnowledgeBase,
  createKnowledgeBase,
  isBuiltin,
  executeBuiltin,
  getBuiltinList,
  SLDResolver,
  createResolver,
  queryKnowledgeBase,
  formatSolutions,
  formatProofTree,
  formatProofPath,
  extractProofPaths,
  analyzeProofTree,
  pruneProofTree,
  proofTreeToMermaid,
  proofTreeToJSON,
  createNLToQueryPrompt,
  createNLToFactsPrompt,
  createNLToRulesPrompt,
  createExplainResultPrompt,
  createGenerateQueriesPrompt,
  createDebugQueryPrompt,
  formatQueryForLLM,
  formatClauseForLLM,
  formatKnowledgeBaseForLLM,
  parseLLMQueryResponse,
  parseLLMFactsResponse,
  type KnowledgeBaseOptions,
  type BuiltinResult,
  type ProofTreeOptions,
  type ProofPath,
  type ProofStats,
  type NLToLogicPromptContext,
  type NLToFactsPromptContext,
  type NLToRulesPromptContext,
  type ExplainResultPromptContext,
  type GenerateQueriesPromptContext,
  type DebugQueryPromptContext,
  type ParseLLMResponseResult,
} from './logic';

export {
  executeQuery,
  GraphQueryBuilder,
  variable as graphVariable,
  parseQueryString,
  formatQueryResult,
  analyzeNLQuery,
  buildQueryFromAnalysis,
  executeNLQuery,
  createNLToGraphQueryPrompt,
  parseNLQueryResponse,
  suggestQuestions,
  generateClarifications,
  ReasoningEngine,
  createReasoningEngine,
  findPath,
  multiHopQuery,
  inferTransitiveRelations,
  inferInverseRelations,
  inferComposedRelations,
  runFullInference,
  createGraphContextPrompt,
  createQueryExplanationPrompt,
  createPathExplanationPrompt,
  createEntityExtractionPrompt,
  createReasoningExplanationPrompt,
  createGraphSummaryPrompt,
  parseEntityExtractionResponse,
  formatNodeForPrompt,
  formatEdgeForPrompt,
  formatPathForPrompt,
  type QueryExecutionContext,
  type ParsedPattern,
  type NLQueryContext,
  type NLQueryAnalysis,
  type NLQueryPromptContext,
  type QueryClarification,
  type ReasoningConfig,
  type ReasoningContext,
  type ReasoningResult,
  type ReasoningStep,
  type CompositionRule,
  type GraphContextForPrompt,
  type QueryToNLContext,
  type PathExplanationContext,
  type EntityExtractionContext,
  type ReasoningExplanationContext,
  type GraphSummaryContext,
} from './knowledge-graph';

export {
  Expr,
  ConstraintBuilder,
  variable as constraintVariable,
  constant,
  and,
  or,
  not,
  implies,
  iff,
  ite,
  sum,
  product,
  allDifferent,
  atMost,
  atLeast,
  exactly,
  expressionToString,
  constraintToString,
  problemToString,
  SimpleSATSolver,
  createSimpleSATSolver,
  solveSAT,
  Z3WASMSolver,
  createZ3Solver,
  solveWithZ3,
  isZ3Available,
  createNLToConstraintsPrompt,
  createConstraintExplanationPrompt,
  createUnsatAnalysisPrompt,
  createConstraintSuggestionPrompt,
  parseNLConstraintsResponse,
  formatSolverResultForLLM,
  formatProblemSummary,
  solve,
  type SimpleSATConfig,
  type Z3SolverConfig,
  type NLToConstraintsContext,
  type ConstraintExplanationContext,
  type UnsatAnalysisContext,
  type ConstraintSuggestionContext,
  type ParseNLConstraintsResult,
} from './constraints';

export {
  ActionSchemaBuilder,
  ActionRegistry,
  createAction,
  evaluatePrecondition,
  applyEffect,
  applyAction,
  schemaToString,
  preconditionToString,
  effectToString,
  actionToString,
  PlanValidator,
  validatePlan,
  simulatePlan,
  formatValidationResult,
  InvariantChecker,
  createInvariantChecker,
  formatInvariantResults,
  commonSafetyProperties,
  PlanRepairer,
  createPlanRepairer,
  repairPlan,
  formatRepairResult,
  createPlanGenerationPrompt,
  createValidationExplanationPrompt,
  createRepairExplanationPrompt,
  createInvariantViolationPrompt,
  createActionSuggestionPrompt,
  parsePlanResponse,
  parseActionSuggestionResponse,
  formatPlanForPrompt,
  formatStateForPrompt,
  formatActionsForPrompt,
  type ValidationConfig,
  type InvariantCheckerConfig,
  type RepairConfig,
  type PlanGenerationContext,
  type PlanValidationPromptContext,
  type PlanRepairPromptContext,
  type InvariantViolationContext,
  type ActionSuggestionContext,
  type ParsePlanResult,
  type ParseActionSuggestionResult,
} from './planning';
